######################################################################
# Automatically generated by qmake (3.0) ?? 9? 3 21:41:17 2016
######################################################################

TEMPLATE = app
TARGET = myQsort
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h myqsort.h recorder.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp myqsort.cpp recorder.cpp

QT += core gui
QT += widgets

